# Generated by Django 3.1.2 on 2020-11-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
