# Generated by Django 3.1.2 on 2020-11-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0002_auto_20201119_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='zoom_link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
