# Generated by Django 3.1.2 on 2020-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0005_auto_20201119_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('0', 'Poniedziałek'), ('1', 'Wtorek'), ('2', 'Środa'), ('3', 'Czwartek'), ('4', 'Piątek'), ('5', 'Sobota'), ('6', 'Niedziela')], max_length=2),
        ),
    ]
