# Generated by Django 3.1.2 on 2020-11-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0006_auto_20201120_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Pn'), ('Wtorek', 'Wt'), ('2', 'Środa'), ('3', 'Czwartek'), ('4', 'Piątek'), ('5', 'Sobota'), ('6', 'Niedziela')], max_length=13),
        ),
    ]
