# Generated by Django 3.1.2 on 2020-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0007_auto_20201120_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedzialek'), ('Wtorek', 'Wtorek'), ('Środa', 'Sroda'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piatek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=13),
        ),
    ]
