# Generated by Django 3.1.2 on 2020-11-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration_app', '0008_auto_20201120_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule', to='administration_app.Schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedzialek'), ('Wtorek', 'Wtorek'), ('Środa', 'Sroda'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piatek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], max_length=12),
        ),
    ]
